"""change time book

Revision ID: 5fdce4b019b3
Revises: 0343575266d4
Create Date: 2025-09-08 13:50:41.368350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5fdce4b019b3'
down_revision: Union[str, Sequence[str], None] = '0343575266d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'updated_at',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('books', 'deleted_at',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('books', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
