"""add picture field to books

Revision ID: b4635817bfd5
Revises: 3c565874ce62
Create Date: 2025-09-08 13:05:53.747633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4635817bfd5'
down_revision: Union[str, Sequence[str], None] = '3c565874ce62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('picture', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'picture')
    # ### end Alembic commands ###
